<?php

class Animal {
    protected string $name;

    public function __construct($name){
        $this->name = $name;
    }

    public function __toString(): string{
        return " Animal [ name={$this->name}]";
    }
}

class Mammal extends Animal {
    public function __construct($name)
    {
        parent:: __construct($name);
    }
    public function __toString()
    {
        return " Mammal[" . parent::__toString() . "]"; // TODO: Change the autogenerated stub
    }
}

class Cat extends Mammal{
    public string $greet;
    public function __construct($name, $greet)
    {
        parent::__construct($name);
        $this->greet = $greet;
        echo " Meow ";
    }
    public function __toString()
    {
        return " Cat [" .  parent::__toString() . "]"; // TODO: Change the autogenerated stub
    }
}

class Dog extends Mammal{
    public string $greet;
    public function __construct($name, $greet)
    {
        parent::__construct($name);
        $this->greet = $greet;
        echo " Woof ";
    }
    public function __toString()
    {
        return " Dog [" .  parent::__toString() . "]"; // TODO: Change the autogenerated stub
    }
}
function concat($str1, $str2, $delimiter): string
{
    return $str1 . $delimiter . $str2;
}

$animal = new Animal("Angel");
echo $animal . PHP_EOL;

$mammal = new Mammal("Santos");
echo $mammal . PHP_EOL;

$cat = new Cat("Misko", "Meow");
echo $cat . PHP_EOL;

$dog = new Dog("Kiki", "Woof");
echo $dog . PHP_EOL;

$message = concat('Hi', 'there!', ' ');
echo $message;